id: A33D8D31D
title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse Chökyi
  Lodrö
type: translation
pechas:
- I1EBAA424
- ID1FFD4F0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:31.805182
  last_modified_at: 2023-01-04 12:01:31.805193
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I1EBAA424/8D6F: AA4D
  ID1FFD4F0/A28A: AA4D
